// <auto-generated />
namespace Radcc.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Start : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Start));
        
        string IMigrationMetadata.Id
        {
            get { return "201609270847557_Start"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
